# Generated by Django 2.1.3 on 2019-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
